config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#mail"

  resource :session, only: [:new, :create, :destroy] do
    post :create_guest
  end

  resources :users, only: [:new]

  namespace :api, defaults: { format: :json } do
    resources :emails, except: [:new, :edit]

    get "/search", to: "email_threads#search"
    resource  :user
    resources :thread_labels, only: [:create, :destroy]

    resource :session do
      post :fetch
    end

    resources :email_threads, only: [:show, :destroy, :update] do
      collection do
        get    :inbox
        get    :starred
        get    :sent
        get    :drafts
        get    :trash
        post   :move_to_trash
        post   :recover
        delete :discard_drafts
      end

      resources :labels, only: [:index]
    end

    resources :labels, except: [:new, :edit, :update] do
      member do
        get :threads
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :first_name, :last_name,
            :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates_uniqueness_of :username

  attr_reader :password

  after_initialize :ensure_session_token
  after_initialize :ensure_email

  has_many :contacts,
    class_name: "Contact",
    foreign_key: :owner_id

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user
      user.is_password?(password) ? user : nil
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_email
    self.email ||= self.username + '@maildog.xyz'
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    render json: current_user
  end

  def create
    @user = User.new(user_params)
    if !@user.save
      render json: @user.errors.full_messages, status: :unprocessable_entity
    else
      log_in!(@user)
      user_contact = @user.contacts.new(user_contact_params)
      user_contact.email = @user.email
      user_contact.save!
      render json: @user
    end
  end

  def user_params
    params.require(:user)
          .permit(:username, :password, :first_name, :last_name, :gender)
  end

  def user_contact_params
    params.require(:user).permit(:first_name, :last_name, :gender)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_current_user

  def new
    render :new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<header class='header'>
  <div class='dog-logo'></div>
  <aside>
    <a class='blue-button' href='<%= new_session_url %>'>Sign in</a>
  </aside>
</header>

<h1 class='create-new-account-header-text'>Create your Maildog account!</h1>

<form class='create-account-form group' id='create-account-form'>
  <label>Name</label>
  <input type='text' for='Name' name='user[first_name]'
                     placeholder="First" class='sign-up-first-name'>

  <input type='text' for='Name' name='user[last_name]'
                     placeholder="Last" class='sign-up-last-name'>
  </label>

  <label>Choose your username</label>
  <input type='text' name='user[username]'
         for='Choose your username'>

  <label>Create a password</label>
  <input type='password' name='user[password]' class='sign-up-password'
         for='Create a password'>

  <label>Confirm your password</label>
  <input type='password' name='confirmPassword' class='sign-up-confirm-password'
         for='Confirm your password'>

  <label>Birthday</label>
  <select name='birthday-month' for='Birthday'>
    <option>January</option>
    <option>February</option>
    <option>March</option>
    <option>April</option>
    <option>May</option>
    <option>June</option>
    <option>July</option>
    <option>August</option>
    <option>September</option>
    <option>October</option>
    <option>November</option>
    <option>December</option>
  </select>
  <input name='birthday-day' type='text' placeholder="Day" for='Birthday'>
  <input name='birthday-year' type='text' placeholder="Year" for='Birthday'>

  <label>Gender</label>
  <select name="user[gender]" for='Gender'>
    <option value="" disabled selected style='display:none;'>I am</option>
    <option value='M'>Male</option>
    <option value='F'>Female</option>
    <option value='O'>Other</option>
  </select>

  <input type='checkbox' for='I agree to be awesome!'
         class='sign-up-checkbox'>
  <label class='sign-up-awesome-label'>I agree to be awesome!</label>

  <button class='blue-button'>Create account</button>
</form>